const STORAGE_KEY='sobertrack-state-v1';
const ETHANOL_DENSITY=0.789;
const ELIMINATION_PER_MINUTE=0.0025;
const $=s=>document.querySelector(s);
let lastPlan=null,timers=[];
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function state(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{drinks:[],profile:{}}}catch{return{drinks:[],profile:{}}}}
function profile(){const s=state();return{weight:Number($('#weight')?.value)||s.profile?.weight||70,sex:$('#sex')?.value||s.profile?.sex||'male',stomach:$('#stomach')?.value||s.profile?.stomach||'empty',limit:Number($('#limit')?.value)||s.profile?.limit||0.3}}
function selectedDrink(){const cat=$('#category')?.value||'manual',s=state(),ratio=Number(s.fillRatio??0.35),ice=Number($('#ice')?.value||s.ice||0);if(cat==='manual'){const ml=Math.max(0,Number($('#manualMl')?.value)||0);return{name:($('#manualBrand')?.value||'Bebida manual').trim(),abv:clamp(Number($('#manualAbv')?.value)||0,0,80),ml,servingMl:ml,cat,unit:'servicio'}}const text=$('#drink')?.selectedOptions?.[0]?.textContent||'Bebida',servText=$('#serving')?.selectedOptions?.[0]?.textContent||'envase',servingMl=Number($('#serving')?.value)||0,abv=Number((text.match(/([0-9]+(?:[.,][0-9]+)?)%/)?.[1]||'0').replace(',','.')),name=text.replace(/\s·\s[0-9]+(?:[.,][0-9]+)?%/,'');if(cat==='spirits'){const cap=Math.max(40,servingMl),iceMl=ice*30,physical=cap*ratio,ml=clamp(physical-iceMl,0,Math.max(0,cap-iceMl));return{name,abv,ml,servingMl:cap,cat,unit:'base alcohólica'}}return{name,abv,ml:servingMl,servingMl,cat,unit:(servText.split(':')[0]||'envase')}}
const grams=(ml,abv)=>ml*(abv/100)*ETHANOL_DENSITY;
function absorption(p,meal,hydration){return(p.stomach==='full'?90:30)*meal*hydration}
function bacAt(t,drinks,p){const r=p.sex==='female'?0.55:0.68,w=p.weight||70;let absorbed=0;for(const d of drinks){const m=(t-d.time)/60000;if(m>0)absorbed+=d.grams*clamp(m/d.absorption,0,1)}const raw=absorbed/(w*r),first=drinks[0]?.time??t,elapsed=Math.max(0,(t-first)/60000);return Math.max(0,raw-ELIMINATION_PER_MINUTE*elapsed)}
function todayAt(v){const now=new Date(),parts=(v||'').split(':').map(Number),d=new Date(now);d.setHours(Number.isFinite(parts[0])?parts[0]:now.getHours(),Number.isFinite(parts[1])?parts[1]:now.getMinutes(),0,0);return d.getTime()}
const label=t=>new Date(t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
function peak(drinks,from,to,p){let best={time:from,bac:0};for(let t=from;t<=to;t+=5*60000){const b=bacAt(t,drinks,p);if(b>best.bac)best={time:t,bac:b}}return best}
function recovery(drinks,from,to,p,threshold){let seenPeak=false,last=0;for(let t=from;t<=to;t+=5*60000){const b=bacAt(t,drinks,p);if(b>=last){last=b;seenPeak=true}else if(seenPeak&&b<=threshold)return t}return null}
function slotDose(plan,t,drink,p,abs,threshold,horizon,maxMl){const check=ml=>peak([...plan,{time:t,grams:grams(ml,drink.abv),absorption:abs}],t,horizon,p).bac;if(check(maxMl)<=threshold)return maxMl;let lo=0,hi=maxMl;for(let i=0;i<22;i++){const mid=(lo+hi)/2;if(check(mid)<=threshold)lo=mid;else hi=mid}return Math.floor(lo)}
function buildPlan(){defaults();const s=state(),p=profile(),drink=selectedDrink(),interval=clamp(Number($('#planInterval')?.value)||30,10,180),meal=Number($('#planMeal')?.value)||1,hydr=Number($('#planHydration')?.value)||1,threshold=Math.max(0.05,(p.limit||0.3)*(Number($('#planMargin')?.value)||0.9)),max=clamp(Number($('#planMaxServes')?.value)||12,1,24);let start=todayAt($('#planStart')?.value),end=todayAt($('#planEnd')?.value);if(end<=start)end+=24*60*60000;const result=$('#planResult');if(!drink.ml||!drink.abv||grams(drink.ml,drink.abv)<=0){result.className='plan-result bad';result.textContent='Selecciona una bebida con volumen y graduación mayores que cero.';$('#planSchedule').innerHTML='';return null}const base=(s.drinks||[]).map(d=>({...d,absorption:d.absorption||absorption(p,1,1)})),abs=absorption(p,meal,hydr),horizon=end+4*60*60000,planned=[],events=[];let count=0;for(let t=start;t<=end&&count<max;t+=interval*60000,count++){const current=[...base,...planned],dose=slotDose(current,t,drink,p,abs,threshold,horizon,drink.cat==='spirits'||drink.cat==='manual'?drink.ml:drink.servingMl);if(dose<=0){events.push({time:t,ml:0,text:`${label(t)} · pausa recomendada: agua/comida y revisión más tarde.`});continue}planned.push({time:t,grams:grams(dose,drink.abv),absorption:abs});if(drink.cat==='spirits'||drink.cat==='manual')events.push({time:t,ml:dose,text:`${label(t)} · si decides consumir, no más de ${dose} ml de ${drink.unit} (${drink.name}).`});else{const pct=Math.round((dose/drink.servingMl)*100);events.push({time:t,ml:dose,text:dose>=drink.servingMl*.98?`${label(t)} · máximo 1 ${drink.unit} completo (${Math.round(drink.servingMl)} ml).`:`${label(t)} · máximo ${dose} ml de ${drink.unit} (${pct}% del envase).`})}}const all=[...base,...planned],pk=peak(all,start,horizon,p),rec=recovery(all,start,horizon,p,threshold),taken=events.filter(e=>e.ml>0),skipped=events.length-taken.length,totalMl=taken.reduce((a,e)=>a+e.ml,0),totalG=grams(totalMl,drink.abv);result.className=pk.bac<=threshold?'plan-result ok':'plan-result warn';result.innerHTML=`<strong>Plan de moderación estimado.</strong><br>${drink.name} (${drink.abv}%). Objetivo preventivo: ${threshold.toFixed(2)} g/L. Entre ${label(start)} y ${label(end)}, con revisiones cada ${interval} min: ${taken.length} recomendación(es) de consumo reducido y ${skipped} pausa(s). Total orientativo: ${Math.round(totalMl)} ml (${totalG.toFixed(1)} g alcohol). Pico: ${pk.bac.toFixed(2)} g/L a las ${label(pk.time)}. ${rec?`Vuelve bajo objetivo hacia ${label(rec)}.`:'No vuelve bajo objetivo en la ventana extendida.'}`;lastPlan={all,events,pk,rec,p,threshold,start,end,horizon};render(events);draw(lastPlan);return lastPlan}
function render(events){const list=$('#planSchedule');list.innerHTML='';events.forEach(e=>{const li=document.createElement('li');li.textContent=e.text;list.append(li)})}
function draw(plan){const c=$('#planCurve');if(!c)return;const ctx=c.getContext('2d'),w=c.width,h=c.height,left=44,right=w-24,top=22,bottom=h-34,max=Math.max(1,plan.threshold*1.5,plan.pk.bac*1.2),x=t=>left+(t-plan.start)/(plan.horizon-plan.start)*(right-left),y=b=>bottom-b/max*(bottom-top);ctx.clearRect(0,0,w,h);ctx.fillStyle='#08111f';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(159,176,200,.25)';[0,plan.threshold,max].forEach(v=>{ctx.beginPath();ctx.moveTo(left,y(v));ctx.lineTo(right,y(v));ctx.stroke();ctx.fillStyle='rgba(229,242,255,.7)';ctx.font='11px system-ui';ctx.fillText(v.toFixed(2),6,y(v)+4)});ctx.strokeStyle='#f59e0b';ctx.setLineDash([8,6]);ctx.beginPath();ctx.moveTo(left,y(plan.threshold));ctx.lineTo(right,y(plan.threshold));ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#38bdf8';ctx.lineWidth=4;ctx.beginPath();let first=true;for(let t=plan.start;t<=plan.horizon;t+=5*60000){const px=x(t),py=y(bacAt(t,plan.all,plan.p));if(first){ctx.moveTo(px,py);first=false}else ctx.lineTo(px,py)}ctx.stroke();ctx.fillStyle='#e5f2ff';ctx.font='16px system-ui';ctx.fillText('Curva prevista del plan',left,17);ctx.font='11px system-ui';ctx.fillText(label(plan.start),left,h-10);ctx.fillText(label(plan.end),x(plan.end)-18,h-10);ctx.fillText('recuperación',right-70,h-10);plan.events.filter(e=>e.ml>0).forEach(e=>{ctx.beginPath();ctx.arc(x(e.time),y(bacAt(e.time,plan.all,plan.p)),4,0,Math.PI*2);ctx.fill()})}
function defaults(){const st=$('#planStart'),en=$('#planEnd');if(!st||!en||st.value)return;const n=new Date();st.value=`${String(n.getHours()).padStart(2,'0')}:${String(n.getMinutes()).padStart(2,'0')}`;const later=new Date(n.getTime()+4*60*60000);en.value=`${String(later.getHours()).padStart(2,'0')}:${String(later.getMinutes()).padStart(2,'0')}`}
async function notify(){if(!lastPlan)buildPlan();if(!('Notification'in window)){alert('Este navegador no soporta notificaciones.');return}const perm=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(perm!=='granted'){alert('No se han activado las notificaciones.');return}timers.forEach(clearTimeout);timers=[];const now=Date.now();lastPlan.events.forEach(e=>{const d=e.time-now;if(d>0&&d<12*60*60*1000)timers.push(setTimeout(()=>new Notification('SoberTrack',{body:e.text}),d))});if(lastPlan.pk.time>now)timers.push(setTimeout(()=>new Notification('SoberTrack · pico estimado',{body:`Pico estimado ${lastPlan.pk.bac.toFixed(2)} g/L. No es medición real.`}),lastPlan.pk.time-now));if(lastPlan.rec&&lastPlan.rec>now)timers.push(setTimeout(()=>new Notification('SoberTrack · recuperación',{body:'Estimación bajo tu objetivo preventivo.'}),lastPlan.rec-now));alert('Avisos activados mientras el navegador/PWA lo permita.')}
function bind(){defaults();$('#planBtn')?.addEventListener('click',buildPlan);$('#notifyPlanBtn')?.addEventListener('click',notify);['planStart','planEnd','planInterval','planMargin','planMeal','planHydration','planMaxServes','category','drink','serving','ice','manualAbv','manualMl','weight','sex','stomach','limit'].forEach(id=>{const el=$(`#${id}`);if(el)el.addEventListener('change',()=>{$('#planResult').textContent='Pulsa calcular para actualizar el plan.';$('#planSchedule').innerHTML=''})})}
bind();
