const $=s=>document.querySelector(s);const KEY='sobertrack-state-v1';
const DB={spirits:[{id:'gin-beefeater',brand:'Beefeater',type:'Ginebra',abv:40,servings:[['Chupito',40],['Copa',50],['Combinado',250]]},{id:'rum-bacardi',brand:'Bacardi',type:'Ron blanco',abv:37.5,servings:[['Chupito',40],['Copa',50],['Combinado',250]]},{id:'vodka-smirnoff',brand:'Smirnoff',type:'Vodka',abv:37.5,servings:[['Chupito',40],['Copa',50],['Combinado',250]]},{id:'whisky-jw',brand:'Johnnie Walker',type:'Whisky',abv:40,servings:[['Chupito',40],['Copa',50],['Vaso',60]]}],beers:[{id:'mahou',brand:'Mahou',type:'Lager',abv:5.5,servings:[['Caña',200],['Tercio',333],['Pinta',568]]},{id:'estrella',brand:'Estrella Galicia',type:'Lager',abv:5.5,servings:[['Caña',200],['Tercio',333],['Pinta',568]]},{id:'ipa',brand:'IPA genérica',type:'IPA',abv:6.5,servings:[['Media pinta',284],['Pinta',568]]}],wines:[{id:'rioja',brand:'Rioja',type:'Tinto',abv:13.5,servings:[['Copa',100],['Copa generosa',150],['Botella',750]]},{id:'verdejo',brand:'Verdejo',type:'Blanco',abv:12.5,servings:[['Copa',100],['Copa generosa',150],['Botella',750]]},{id:'cava',brand:'Cava',type:'Espumoso',abv:11.5,servings:[['Flauta',100],['Copa',150],['Botella',750]]}]};
const state=load()||{profile:{weight:70,sex:'male',stomach:'empty',limit:.3},drinks:[],waterBoost:false,reflexBase:null,fillRatio:.38,ice:0};let deferredInstall=null,reflexTimer=null,reflexArmed=false,reflexStart=0;
function load(){try{return JSON.parse(localStorage.getItem(KEY))}catch{return null}}function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function catLabel(k){return{spirits:'Destilados',beers:'Cervezas',wines:'Vinos'}[k]}function currentDrink(){return DB[$('#category').value].find(d=>d.id===$('#drink').value)}function currentServing(){return Number($('#serving').value)}
function init(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null;$('#installBtn').classList.add('hidden')}};hydrateUI();bind();drawAll()}
function hydrateUI(){$('#weight').value=state.profile.weight;$('#sex').value=state.profile.sex;$('#stomach').value=state.profile.stomach;$('#limit').value=state.profile.limit;$('#ice').value=state.ice;for(const k of Object.keys(DB))$('#category').add(new Option(catLabel(k),k));$('#category').value='spirits';fillDrinks()}
function fillDrinks(){const cat=$('#category').value;$('#drink').innerHTML='';DB[cat].forEach(d=>$('#drink').add(new Option(`${d.brand} · ${d.type} · ${d.abv}%`,d.id)));fillServings()}
function fillServings(){const d=currentDrink();$('#serving').innerHTML='';d.servings.forEach(([name,ml])=>$('#serving').add(new Option(`${name}: ${ml} ml`,ml)));updateGlassStats()}
function bind(){$('#category').onchange=fillDrinks;$('#drink').onchange=fillServings;$('#serving').onchange=drawAll;$('#ice').oninput=()=>{state.ice=clamp(Number($('#ice').value)||0,0,8);save();drawAll()};$('#saveProfile').onclick=()=>{state.profile={weight:+$('#weight').value||70,sex:$('#sex').value,stomach:$('#stomach').value,limit:+$('#limit').value||.3};save();drawAll()};$('#addDrink').onclick=addDrink;$('#waterBtn').onclick=()=>{state.waterBoost=true;save();drawAll()};$('#resetBtn').onclick=()=>{if(confirm('¿Borrar sesión local?')){localStorage.removeItem(KEY);location.reload()}};$('#exportBtn').onclick=exportData;$('#reflexBtn').onclick=reflex;const g=$('#glass');['pointerdown','pointermove'].forEach(ev=>g.addEventListener(ev,e=>{if(e.buttons||ev==='pointerdown')setFill(e)}));}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}function glassMetrics(){return{x:55,y:45,w:150,h:330,cap:300}}function setFill(e){const r=$('#glass').getBoundingClientRect(),m=glassMetrics(),scale=$('#glass').width/r.width,y=(e.clientY-r.top)*scale;state.fillRatio=clamp(1-(y-m.y)/m.h,0,1);save();drawAll()}
function volumes(){const m=glassMetrics(),cap=currentServing(),iceMl=(+$('#ice').value||0)*30,physical=cap*state.fillRatio,spirit=clamp(physical-iceMl,0,cap-iceMl),mixer=clamp(cap-iceMl-spirit,0,cap);return{cap,iceMl,spirit,mixer}}
function drawGlass(){const c=$('#glass'),ctx=c.getContext('2d'),m=glassMetrics(),v=volumes();ctx.clearRect(0,0,c.width,c.height);ctx.lineWidth=5;ctx.strokeStyle='rgba(229,242,255,.85)';ctx.fillStyle='rgba(255,255,255,.03)';ctx.beginPath();ctx.moveTo(m.x,m.y);ctx.lineTo(m.x+m.w,m.y);ctx.lineTo(m.x+m.w-25,m.y+m.h);ctx.lineTo(m.x+25,m.y+m.h);ctx.closePath();ctx.fill();ctx.stroke();const iceH=m.h*(v.iceMl/m.cap),fillH=m.h*state.fillRatio,base=m.y+m.h;ctx.fillStyle='rgba(191,219,254,.7)';for(let i=0;i<+$('#ice').value;i++){const row=Math.floor(i/3),col=i%3;ctx.fillRect(m.x+35+col*33,base-28-row*30,24,20)}ctx.fillStyle='rgba(56,189,248,.35)';ctx.fillRect(m.x+25,base-fillH,m.w-50,fillH);ctx.fillStyle='rgba(34,197,94,.55)';ctx.fillRect(m.x+25,base-iceH-(m.h*(v.spirit/m.cap)),m.w-50,m.h*(v.spirit/m.cap));ctx.fillStyle='#e5f2ff';ctx.font='15px system-ui';ctx.fillText('Arrastra el nivel',68,405);updateGlassStats()}
function updateGlassStats(){const d=currentDrink(),v=volumes();$('#spiritMl').textContent=Math.round(v.spirit)+' ml';$('#mixerMl').textContent=Math.round(v.mixer)+' ml';$('#abvText').textContent=d.abv+'%'}
function addDrink(){const d=currentDrink(),v=volumes(),ml=$('#category').value==='spirits'?v.spirit:currentServing();if(ml<=0)return alert('Marca un volumen mayor que cero.');const absorption=($('#stomach').value==='full'?90:30)*(state.waterBoost?1.1:1);state.drinks.push({id:crypto.randomUUID(),time:Date.now(),brand:d.brand,type:d.type,abv:d.abv,ml,grams:ml*(d.abv/100)*.789,absorption});state.waterBoost=false;save();drawAll()}
function bacAt(t){const r=state.profile.sex==='female'?.55:.68,w=state.profile.weight||70,beta=.0025;let absorbed=0;for(const d of state.drinks){const mins=(t-d.time)/60000;if(mins<=0)continue;absorbed+=d.grams*clamp(mins/d.absorption,0,1)}let raw=absorbed/(w*r);const first=state.drinks[0]?.time??t;const elapsed=Math.max(0,(t-first)/60000);return Math.max(0,raw-beta*elapsed)}
function curve(){const now=Date.now(),pts=[];for(let i=0;i<=240;i+=5)pts.push({min:i,bac:bacAt(now+i*60000)});return pts}
function drawChart(){const c=$('#chart'),ctx=c.getContext('2d'),pts=curve(),w=c.width,h=c.height,p=34,max=Math.max(.8,state.profile.limit*1.3,...pts.map(p=>p.bac))*1.08;ctx.clearRect(0,0,w,h);ctx.fillStyle='#08111f';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(159,176,200,.25)';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=p+(h-2*p)*i/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}const ly=h-p-(state.profile.limit/max)*(h-2*p);ctx.strokeStyle='#f59e0b';ctx.setLineDash([8,6]);ctx.beginPath();ctx.moveTo(p,ly);ctx.lineTo(w-p,ly);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#38bdf8';ctx.lineWidth=4;ctx.beginPath();pts.forEach((pt,i)=>{const x=p+(pt.min/240)*(w-2*p),y=h-p-(pt.bac/max)*(h-2*p);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#e5f2ff';ctx.font='18px system-ui';ctx.fillText('BAC g/L · 4h',p,26);const now=bacAt(Date.now()),peak=pts.reduce((a,b)=>b.bac>a.bac?b:a,pts[0]);$('#bacNow').textContent=now.toFixed(2)+' g/L';$('#bacPeak').textContent=peak.bac.toFixed(2)+' g/L';$('#peakTime').textContent=peak.min?`en ${peak.min} min`:'ahora';const over=pts.find(p=>p.bac>state.profile.limit);const box=$('#alert');if(over){box.className='alert bad';box.textContent=`¡Alto! El alcohol ingerido subirá en ${over.min} minutos y superarás tu límite de ${state.profile.limit} g/L.`}else{box.className='alert ok';box.textContent='Sin riesgo proyectado por encima de tu límite.'}}
function renderHistory(){const ul=$('#history');ul.innerHTML='';state.drinks.slice().reverse().forEach(d=>{const li=document.createElement('li');li.textContent=`${new Date(d.time).toLocaleTimeString()} · ${d.brand} ${d.type} · ${Math.round(d.ml)} ml · ${d.grams.toFixed(1)} g alcohol`;ul.append(li)});$('#waterState').textContent=state.waterBoost?'Bonus activo: la siguiente copa se absorberá un 10% más lenta.':'Sin bonus de hidratación activo.'}
function reflex(){const b=$('#reflexBtn'),out=$('#reflexResult');if(reflexArmed){const ms=performance.now()-reflexStart;reflexArmed=false;b.classList.remove('ready');b.textContent='Empezar de nuevo';if(!state.reflexBase)state.reflexBase=ms;const dev=((ms-state.reflexBase)/state.reflexBase)*100;out.textContent=`Tiempo: ${Math.round(ms)} ms. Base: ${Math.round(state.reflexBase)} ms. Desviación: ${Math.round(dev)}%. ${dev>25?'Mejor pasa a bebidas sin alcohol y vuelve acompañado/a.':'Dentro de tu referencia de la noche.'}`;save();return}b.textContent='Espera...';out.textContent='Pulsa solo cuando se ponga verde.';clearTimeout(reflexTimer);reflexTimer=setTimeout(()=>{reflexArmed=true;reflexStart=performance.now();b.classList.add('ready');b.textContent='¡Pulsa ahora!'},900+Math.random()*2200)}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`sobertrack-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function drawAll(){drawGlass();drawChart();renderHistory()}init();
